- name: Install php-pear
  apt: pkg="php-pear" state=present
  when: php5.pecl_packages is defined

- name: Install php5.6-dev
  apt: pkg="php5.6-dev" state=present
  when: php5.pecl_packages is defined

- name: Install Package
  shell: echo "\n\n\n\n\n\n\n\n\n" | pecl install {{ item }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  with_items: php5.pecl_packages
  when: php5.pecl_packages is defined

- name: Create extension .ini file
  template: >
    src="extension.j2"
    dest="/etc/php/5.6/mods-available/{{ item | regex_replace('-[\\w\\.]+$', '') }}.ini"
    owner="root"
    group="root"
    mode=0644
  with_items: php5.pecl_packages
  when: php5.pecl_packages is defined

- name: Enable extension
  shell: php5enmod {{ item | regex_replace('-[\\w\\.]+$', '') }}
  with_items: php5.pecl_packages
  when: php5.pecl_packages is defined
