---
- hosts: all
  become: true
  vars_files:
    - vars/globals.yml
    - vars/locals.yml
  roles:
    - server
    - apache
#    - nginx
    - mysql
#    - pgsql
    - php7
#    - php5
    - wordpress
    - application
